apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: school-payment
  namespace: school-management
  name: school-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: school-payment
  template:
    metadata:
      labels:
        app: school-payment
    spec:
      containers:
        - image: tannkimsour/school-payment:v0.0.1
          name: school-payment
          ports:
            - containerPort: 9093
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis-creds
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis-creds
                  key: port
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: host
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-creds
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: school-payment
  name: school-payment-svc
  namespace: school-management
spec:
  ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    app: school-payment
  type: ClusterIP
